# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);


create table "tickets" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "ticketsCount" int not null,
  "title" varchar not null
);

# --- !Downs

drop table "people" if exists;

drop table "tickets" if exists;
